# Generated by Django 5.2.5 on 2025-08-14 07:15

import baseApp.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=200)),
                ('author', models.CharField(help_text='Author of the book', max_length=100)),
                ('isbn', models.CharField(help_text='ISBN number of the book', max_length=20, unique=True)),
                ('total_copies', models.PositiveIntegerField(help_text='Total number of copies available in the library')),
                ('available_copies', models.PositiveIntegerField(help_text='Number of copies currently available for borrowing')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the book was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time when the book record was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the genre', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the genre', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the book was borrowed.')),
                ('due_date', models.DateField(default=baseApp.models.default_due_date, help_text='Date when the book should be returned.')),
                ('return_date', models.DateField(blank=True, help_text='Date when the book was actually returned.', null=True)),
                ('status', models.CharField(choices=[('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='BORROWED', help_text='Current status of the borrowing record.', max_length=10)),
                ('book', models.ForeignKey(help_text='The book being borrowed.', on_delete=django.db.models.deletion.CASCADE, to='baseApp.book')),
                ('member', models.ForeignKey(help_text='The member who borrowed the book.', limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Genre of the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseApp.genre'),
        ),
    ]
