# Generated by Django 5.1.1 on 2025-08-17 16:26

import baseApp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_alter_borrowrecord_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=baseApp.models.default_due_date),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
