# Generated by Django 5.1.1 on 2025-08-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_alter_borrowrecord_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the book was borrow.'),
        ),
    ]
