# Generated by Django 5.2.5 on 2025-08-17 16:42

import baseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_alter_borrowrecord_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=baseApp.models.default_due_date, help_text='Due date for returning the book (default: 14 days from borrow date).'),
        ),
    ]
