# Generated by Django 5.2.5 on 2025-08-18 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateTimeField(help_text='Time when the book was borrow.', verbose_name=datetime.date(2025, 8, 18)),
        ),
    ]
