# Generated by Django 5.2.5 on 2025-08-18 05:25

import baseApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_alter_borrowrecord_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=datetime.date(2025, 8, 18), help_text='Date when the book was borrowed.'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(default=baseApp.models.default_due_date, help_text='Date when the book should be returned.'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='return_date',
            field=models.DateField(blank=True, help_text='Date when the book was actually returned.', null=True),
        ),
    ]
