# Generated by Django 5.2.5 on 2025-08-18 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_borrowrecord_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
