# Generated by Django 5.2.5 on 2025-08-18 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_alter_borrowrecord_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the book was borrowed.'),
        ),
    ]
