# Generated by Django 5.2.5 on 2025-08-18 05:37

import baseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_alter_borrowrecord_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateTimeField(default=baseApp.models.default_due_date, help_text='Date when the book should be returned.'),
        ),
    ]
