# Generated by Django 5.2.5 on 2025-08-18 05:40

import baseApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_alter_borrowrecord_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateField(default=baseApp.models.get_today, help_text='Date when the book was borrowed.'),
        ),
    ]
